### ISSUE TITLE
is there a row limit?

### ISSUE THREAD

**Issue by L34N07** [FelipeRos19/PowerfulBackpacks#9]
I ve created couple backpacks, but the larger ones doesnt work.  They both wont open

```
  d_block_backpack:
    name: '<grey>Mega Backpack'
    lore:
      - ''
      - '<grey>Its a Mega Backpack'
      - '<grey>Rows: <bold><gold>%backpack_rows%'
      - '<grey>Slots: <bold><gold>%backpack_slots%'
      - ''
    rows: 8
    craft:
      shape:
        - 'III'
        - 'I$I'
        - 'III'
      items:
        I: 'DIAMOND_BLOCK'
        $: 'super_reinforced_backpack'


  netherite_backpack:
    name: '<grey>Ultimate Backpack'
    lore:
      - ''
      - '<grey>Its THE Backpack'
      - '<grey>Rows: <bold><gold>%backpack_rows%'
      - '<grey>Slots: <bold><gold>%backpack_slots%'
      - ''
    rows: 20
    craft:
      shape:
        - 'III'
        - 'I$I'
        - 'III'
      items:
        I: 'NETHERITE_INGOT'
        $: 'd_block_backpack'
```
i mean 20 porbably its too much, but 8? why it doesnt open
